name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - main

jobs:
  firebase-build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install angular cli
        run: npm install -g @angular/cli@15.1.5

      - run: ng build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTAX_1E149 }}'
          channelId: live
          projectId: contax-1e149
